.PHONY: build run test fmt clippy clean

build:
	@cargo build

run:
	@cargo run --bin hello

test:
	@cargo test

fmt:
	@cargo fmt --all

clippy:
	@cargo clippy --all-targets -- -D warnings

clean:
	@cargo clean
